<%@ Control Language="C#" AutoEventWireup="true" Inherits="Widgets.Newsletter.Edit" Codebehind="edit.ascx.cs" %>
<asp:GridView 
  runat="server"
  id="gridEmails"
  AlternatingRowStyle-BackColor="#F1F1F1"
  AutoGenerateColumns="False"
  AutoGenerateDeleteButton="true">
 
  <Columns>
    <asp:BoundField HeaderText="Email" DataField="innertext" />
  </Columns> 
</asp:GridView>