CREATE TABLE [dbo].[LadderWeeks] (
    [Id]         INT      IDENTITY (1, 1) NOT NULL,
    [WeekNumber] INT      NOT NULL,
    [StertDate]  DATETIME NOT NULL,
    [EndDate]    DATETIME NOT NULL,
    [IsCurrent]  BIT      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

