CREATE TABLE [dbo].[Standings] (
    [Id]           INT IDENTITY (1, 1) NOT NULL,
    [LadderWeekId] INT NOT NULL,
    [PlayerId]     INT NOT NULL,
    [Position]     INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

